export const FETCH_QUOTE = 'FETCH_QUOTE';
export const FETCH_QUOTE_START = 'FETCH_QUOTE_START';
export const FETCH_QUOTE_SUCCESS = 'FETCH_QUOTE_SUCCESS';
export const FETCH_QUOTE_FAIL = 'FETCH_QUOTE_FAIL';

export const NEXT_QUOTE = 'NEET_QUOTE';
export const PREVIOUS_QUOTE = 'PREVIOUS_QUOTE';